version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    allow:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "ccxt"
        update-types:
          [
            "version-update:semver-patch",
            "version-update:semver-major",
            "version-update:semver-minor",
          ]
