/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.44.2
  Forc version: 0.40.1
  Fuel-Core version: 0.18.1
*/

export type { PricesAbi } from './PricesAbi';

export { PricesAbi__factory } from './factories/PricesAbi__factory';
