version: "3.9"

services:
  mongodb:
    image: mongo:5.0
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
  monitoring:
    image: monitoring
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    restart: on-failure
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ~/apps/uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: always
