name: Evm Connector CI
on:
  push:
    paths:
      - packages/evm-connector/**
      - .github/workflows/evm-connector-tests.yml

jobs:
  evm-connector-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: packages/evm-connector
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15
      - name: Install modules
        run: yarn
      - name: Compile contracts
        run: yarn compile
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test
        env:
          NODE_ENV: test
