name: Gelato Relayer CI
on:
  push:
    paths:
      - packages/gelato-relayer/**
      - packages/on-chain-relayer/**
      - packages/sdk/**
      - packages/utils/**
      - packages/protocol/**
      - packages/rpc-providers/**
      - packages/evm-connector/**
      - .github/workflows/gelato-relayer-tests.yml

jobs:
  gelato-relayer-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: packages/gelato-relayer
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Run tests
        run: yarn test
        env:
          NODE_ENV: test
          ALCHEMY_ID: ${{ secrets.ALCHEMY_API_KEY }}
