name: Reusable workflow for integration tests

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string

jobs:
  run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15
      - name: Install deps
        run: yarn --frozen-lockfile --immutable
      - name: Build all
        run: |
          STATUS_TMP=$(pwd)/status.tmp
          echo 0 > $STATUS_TMP
          cd packages/cache-service && yarn build || echo 1 > $STATUS_TMP &
          cd packages/evm-connector && yarn compile && yarn build || echo 2 > $STATUS_TMP &
          cd packages/oracle-node && yarn build || echo 3 > $STATUS_TMP &
          cd packages/on-chain-relayer && yarn compile && yarn build || echo 4 > $STATUS_TMP &

          wait
          exit $(cat $STATUS_TMP)
      - name: "Run integration tests: ${{ inputs.command }}"
        working-directory: packages/integration
        run: "${{ inputs.command }}"
        env:
          NODE_ENV: test
