# Automate building a public docker image of on-chain-relayer
# and publishing it to the AWS ECR Public

name: Deploy on-chain relayer to Amazon ECR Public
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - push-docker-ecr-public
    paths:
      - packages/on-chain-relayer/**
      - .github/workflows/on-chain-relayer-deploy-to-ecr.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: ECR public action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build and Push Docker images to ECR public
        id: build-and-push
        run: |
          # Build images
          ON_CHAIN_RELAYER_DOCKER_NAME=public.ecr.aws/y7v2w8b2/redstone-on-chain-relayer
          TAG=$(echo ${GITHUB_SHA} | cut -c1-7)
          docker build -t "$ON_CHAIN_RELAYER_DOCKER_NAME:$TAG" packages/on-chain-relayer/

          # Push images to ECR Public
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
          docker push $ON_CHAIN_RELAYER_DOCKER_NAME:$TAG
