name: Oracle stocks dry run test
on:
  push:
    paths:
      - packages/oracle-node/**
      - .github/workflows/oracle-stocks-dry-run-test.yml

jobs:
  stocks-dry-run-test:
    runs-on: self-hosted
    timeout-minutes: 10
    defaults:
      run:
        working-directory: packages/oracle-node
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Build
        run: yarn build
      - name: Run dry run test
        run: yarn test:stocks-dry-run
        env:
          NODE_ENV: test
          TWELVE_DATA_API_KEY: ${{ secrets.TWELVE_DATA_API_KEY }}
          SKIPPED_SOURCES: '["binance"]'
