# Automate building a public docker image of oracle-monitoring
# and publishing it to the AWS ECR Public

name: Deploy monitoring to Amazon ECR Public
on:
  push:
    branches:
      - main
      - push-docker-ecr-public
    paths:
      - packages/oracle-monitoring/**
      - .github/workflows/oracle-monitoring-deploy-to-ecr-public.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: ECR public action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build and Push Docker images to ECR public
        id: build-and-push
        run: |
          # Build images
          ORACLE_MONITORING_DOCKER_NAME=public.ecr.aws/y7v2w8b2/redstone-oracle-monitoring
          TAG=$(echo ${GITHUB_SHA} | cut -c1-7)
          docker build -t "$ORACLE_MONITORING_DOCKER_NAME:$TAG" packages/oracle-monitoring/

          # Push images to ECR Public
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
          docker push $ORACLE_MONITORING_DOCKER_NAME:$TAG
