name: Starknet Relayer CI
on:
  push:
    paths:
      - packages/starknet-relayer/**
      - packages/starknet-connector/**
      - packages/sdk/**
      - packages/protocol/**
      - .github/workflows/starknet-relayer-tests.yml

jobs:
  starknet-relayer-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: packages/starknet-relayer
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
